version: "3.8"

services:
  backend:
    build:
      context: ./LumenBackend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: ["python", "run.py"]
    volumes:
      - ./LumenBackend:/app
    restart: always

  frontend:
    build:
      context: ./LumenFrontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    volumes:
      - ./LumenFrontend:/usr/src/LumenFrontend
      - /usr/src/LumenFrontend/node_modules
    ports:
      - "3000:3000"
